choco install -y boxstarter
choco install -y google-chrome-x64
choco install -y launchy
choco install -y skype
choco install -y filezilla
choco install -y sumatrapdf
choco install -y 7zip
choco install -y ccleaner
choco install -y spotify
choco install -y atom
choco install -y slack